import re
import json
from typing import Dict, List
import asyncio

from google import genai
from google.genai import types

from shared.llm_client import chat_completion
from .schemas import PaperOutline, OutlineSection, PaperReview, EnrichedDraft

class WritingAgent:
    """A centralized class managing all LLM interactions for the academic writing pipeline asynchronously."""

    def __init__(self, api_config: dict):
        self.api_config = api_config

    async def _call_llm_json(self, prompt: str, schema_cls=None) -> str:
        """Helper to call the shared llm_client enforcing JSON output."""
        messages = [{"role": "user", "content": prompt}]
        response = await chat_completion(
            messages=messages,
            api_config=self.api_config,
            response_format={"type": "json_object"} if schema_cls else None,
            temperature=0.7 if schema_cls is PaperOutline else 0.4
        )
        return response

    async def _call_llm_text(self, prompt: str, temperature: float = 0.2) -> str:
        """Helper to call the shared llm_client for raw text output."""
        messages = [{"role": "user", "content": prompt}]
        response = await chat_completion(
            messages=messages,
            api_config=self.api_config,
            temperature=temperature
        )
        
        # Clean up Markdown LaTeX blocks if the LLM hallucinates them
        text = response
        text = re.sub(r'^```(latex)?\s*', '', text, flags=re.IGNORECASE)
        text = re.sub(r'^```\s*', '', text, flags=re.IGNORECASE)
        text = re.sub(r'\s*```$', '', text)
        return text.strip()

    async def generate_paper_outline(self, context: Dict[str, str]) -> PaperOutline:
        """Agent responsible for outlining the paper."""
        print("Executing Planning Agent...")
        
        md_titles = {}
        if "__md_titles__" in context:
            try:
                md_titles = json.loads(context["__md_titles__"])
            except json.JSONDecodeError:
                pass
                
        context_summary = "Available Context Files:\n"
        for filename in context.keys():
            if filename == "__md_titles__":
                continue
            if filename in md_titles:
                context_summary += f"- {filename} (Title: {md_titles[filename]})\n"
            else:
                context_summary += f"- {filename}\n"
            
        available_images = [f for f in context.keys() if f.endswith(".png")]
        images_instruction = ""
        if available_images:
            images_instruction = f"\nAlso, you MUST allocate the following available PNG images among the sections: {', '.join(available_images)}. EVERY image must be included in the 'images' field of EXACTLY ONE section. Do not leave any image unassigned, and do not assign any image more than once.\n"
        
        research_plan_content = ""
        if "research_plan.md" in context:
            research_plan_content = f"\n--- Content of research_plan.md (The Project Context & Goals) ---\n{context['research_plan.md']}\n"
            
        steps_content = ""
        if "steps.txt" in context:
            steps_content = f"\nHere is the specific steps of the experiment:\n{context['steps.txt']}\n"
            
        prompt = f"""
        You are an expert academic paper planner and editor. Your task is to design the structure of a high-quality academic paper based on the experimental study described in the provided context.
        
        Here is a summary of the available context files generated by previous agents during the experiment:
        {context_summary}
        
        {research_plan_content}
        {steps_content}
        
        Please propose a compelling title and a detailed outline for the paper. For each section in the outline, specify:
        1. The section title (e.g., Introduction, Methodology, Results, Discussion, Conclusion). CRITICAL RULES FOR TITLES:
           - Do NOT include an "Abstract" section. The abstract will be generated separately after the main text is written.
           - Do NOT include any numbers or hardcoded section numbering in the title (e.g., write "Introduction" NOT "1. Introduction"). LaTeX will handle numbering automatically.
        2. A brief description of the section's purpose.
        3. Key bullet points to cover.
        4. Which of the specific available context files are REQUIRED to draft this section accurately.
        5. Which of the available images (PNG files) should be inserted in this section.
        {images_instruction}
        Additionally, extract all references from the provided context (especially any 'References' section at the end of the context files) and output them as a list of unique BibTeX entries in the `references` field. Ensure each reference has a unique `citation_key` that the drafting agent can use. There should be NO DUPLICATE references.

        Ensure the structure follows standard academic conventions (e.g., IEEE or ACM format logic).
        
        You must return the result as a raw JSON string matching this schema:
        {PaperOutline.model_json_schema()}
        """
        
        response_text = await self._call_llm_json(prompt, schema_cls=PaperOutline)
        
        # Gemini JSON might still come with markdown formatting in the shared client
        response_text = re.sub(r'^```json\s*', '', response_text)
        response_text = re.sub(r'\s*```$', '', response_text)
        
        data = json.loads(response_text)
        return PaperOutline(**data)

    async def draft_section(self, section: OutlineSection, context: Dict[str, str], references_info: str = "", full_outline: PaperOutline = None, previously_drafted_text: str = "") -> str:
        """Agent responsible for writing a specific section of the paper in LaTeX."""
        print(f"Executing Drafting Agent for section: {section.title}...")
        
        section_context = ""
        for filename in section.required_context:
            if filename in context:
                section_context += f"\n--- {filename} ---\n{context[filename]}\n"
        
        assigned_images_text = ""
        if hasattr(section, "images") and section.images:
            assigned_images_text = f"You HAVE BEEN ASSIGNED the following image files to include in this section: {', '.join(section.images)}. You MUST include them using \\includegraphics{{filename}}.\n"
        else:
            assigned_images_text = "You HAVE NOT been assigned any images for this section. DO NOT include any \\includegraphics commands.\n"

        outline_context = ""
        if full_outline:
            outline_context = f"The overall title of the paper is: {full_outline.title}\n"
            outline_context += "The complete outline of the paper is as follows:\n"
            for s in full_outline.sections:
                outline_context += f"- {s.title}: {s.description}\n"
                
        continuity_instructions = ""
        if previously_drafted_text:
            continuity_instructions = f"\nCRITICAL CONTINUITY RULES:\n"
            continuity_instructions += "The following raw LaTeX text represents the sections of the paper that HAVE ALREADY BEEN DRAFTED before this section:\n"
            continuity_instructions += f"\n--- PREVIOUSLY DRAFTED SECTIONS ---\n{previously_drafted_text}\n--- END PREVIOUSLY DRAFTED SECTIONS ---\n\n"
            continuity_instructions += "You MUST carefully read the previously drafted sections above.\n"
            continuity_instructions += "Your new section must logically follow this text. CRITICAL: You must maintain absolute consistency with any numbers, dataset counts, thresholds, statistical results, categorical definitions (e.g., what constitutes 'High' or 'Low' p/n ratios), or theoretical premises established in the previous sections. DO NOT contradict them. DO NOT repeat concepts, methodologies, or introductions that are already established in the previous sections.\n"
            
            if full_outline:
                upcoming_sections = []
                found_current = False
                for s in full_outline.sections:
                    if found_current:
                        upcoming_sections.append(s.title)
                    if s.title == section.title:
                        found_current = True
                
                if upcoming_sections:
                    continuity_instructions += f"\nThe following sections WILL BE DRAFTED LATER: {', '.join(upcoming_sections)}.\n"
                    continuity_instructions += "DO NOT deeply discuss those topics here; leave them for their respective sections. Focus ONLY on the requirements of YOUR current section.\n"

        prompt = f"""
        You are an expert academic writer. Your task is to draft the "{section.title}" section of a research paper based on the provided experimental context.
        
        {outline_context}
        {continuity_instructions}
        
        You must output ONLY valid LaTeX code for this section. Do NOT include the \documentclass, \begin{{document}}, or \end{{document}} tags, as this will be included in a larger file. 
        
        CRITICAL FORMATTING RULES:
        1. ONLY use the following packages which are already included in the preamble: cite, amsmath, amssymb, amsfonts, graphicx, textcomp, xcolor, booktabs, hyperref.
        2. NEVER use TikZ, algorithmic, or any other unimported packages.
        3. NEVER hallucinate or assume the existence of any images, PDFs, or files that were not explicitly provided. 
        4. NEVER explicitly mention the names of the context files provided to you (e.g., do not say "Based on the synthesis_report.md" or "According to the final_report"). Instead, synthesize the information naturally into an objective academic tone as if it were your own research.
        5. {assigned_images_text}
        6. To prevent formatting overflow in the two-column IEEE format:
           - Always use \\includegraphics[width=\\linewidth]{{...}} for images.
           - For tables with many columns or long text, use \\resizebox{{\\linewidth}}{{!}}{{\\begin{{tabular}}...\\end{{tabular}}}} or adjust column specifiers (e.g., p{{0.8\\linewidth}}) so they do not exceed the column width.
        7. You MUST start your output with the top-level section heading command (e.g., \\section{{{section.title}}}) to establish the structural hierarchy for the reviewer.
        
        Here are the specific requirements for YOUR section:
        Description: {section.description}
        Key Points to Cover:
        {chr(10).join(['- ' + p for p in section.key_points])}
        
        Here is the relevant experimental context to base your writing on:
        {section_context}
        
        Write the section professionally, clearly, and concisely, adhering strictly to the provided context and outline. Maintain a logical flow from the previous sections.
        
        If you need to cite prior work or specific references provided in the context, you MUST use the following available BibTeX citation keys using standard LaTeX \cite{{key}} commands. 
        Available Citation Keys:
        {references_info}
        """
        
        return await self._call_llm_text(prompt, temperature=0.2)

    async def review_draft(self, full_draft: str, outline: PaperOutline, approved_sections: List[str] = None) -> PaperReview:
        """Agent responsible for reviewing the compiled draft for consistency and flow."""
        print("Executing Review Agent...")
        
        outline_text = f"Expected Outline:\nTitle: {outline.title}\n"
        for sec in outline.sections:
            outline_text += f"- {sec.title}: {sec.description}\n"
            
        approved_text = ""
        if approved_sections and len(approved_sections) > 0:
            approved_text = f"\nCRITICAL INSTRUCTION: The following sections HAVE ALREADY BEEN APPROVED in a previous review cycle: {', '.join(approved_sections)}. YOU MUST NOT request any revisions for these approved sections, even if you spot minor imperfections. Focus ONLY on sections that are NOT in this list.\n"
            
        prompt = f"""
        You are a meticulous peer reviewer and editor for an academic journal. Your task is to review a draft of a research paper based on the provided experimental context.
        {approved_text}
        Here is the intended outline:
        {outline_text}
        
        Here is the full LaTeX draft of the paper:
        \n---\n{full_draft}\n---\n

        Please evaluate the draft for:
        1. Cross-section consistency (do the conclusions match the results? Does the intro align with the methodology?). Pay close attention to numbers, dataset counts, and threshold logic across sections to ensure no contradictions exist.
        2. Logical transitions between sections.
        3. Proper LaTeX formatting and structural integrity. 
        
        NOTE: The provided draft ONLY contains the body text. Do NOT penalize the draft for missing standard LaTeX frontmatter commands (e.g., \\documentclass, \\title, \\begin{{document}}, \\maketitle) as these are intentionally handled by a separate assembly agent.
        
        Provide detailed feedback. If the draft is acceptable (minor formatting issues are fine, but no major logical gaps or inconsistencies), set 'is_approved' to true. Otherwise, set it to false.
        If 'is_approved' is false, you MUST provide a list of 'required_revisions'. For each revision, specify the exact 'section_title' that needs to be rewritten and the specific 'feedback' detailing the changes required for that section to resolve contradictions, formatting issues, or logic gaps.
        
        You must return the result as a raw JSON string matching this schema:
        {PaperReview.model_json_schema()}
        """
        
        response_text = await self._call_llm_json(prompt, schema_cls=PaperReview)
        
        response_text = re.sub(r'^```json\s*', '', response_text)
        response_text = re.sub(r'\s*```$', '', response_text)
        
        data = json.loads(response_text)
        return PaperReview(**data)

    async def generate_abstract(self, full_draft: str, title: str) -> str:
        """Agent responsible for writing the abstract after the full paper is drafted."""
        print("Executing Abstract Agent...")
        
        prompt = f"""
        You are an expert academic writer and editor. A complete research paper titled "{title}" has just been drafted. 
        Your task is to write a highly professional, concise, and compelling Abstract for this paper based *strictly* on the provided draft.
        
        CRITICAL RULES:
        1. Output ONLY the raw text of the abstract. Do NOT include LaTeX tags like \\begin{{abstract}} or \\end{{abstract}}.
        2. The abstract must be a single, cohesive paragraph summarizing the background, methodology, key results, and conclusion of the paper.
        3. NEVER include any citations or references (e.g., no [1] or \cite{{...}}) in the abstract. An abstract must be completely self-contained.
        4. Keep it between 150 and 250 words.
        
        Here is the FULL DRAFT of the paper to summarize:
        \n---\n{full_draft}\n---\n
        """
        
        return await self._call_llm_text(prompt, temperature=0.2)

    async def revise_section(self, section_title: str, current_section_draft: str, section_feedback: str, section_context: str) -> str:
        """Agent responsible for revising a specific section of the draft based on review feedback and context."""
        print(f"Executing Revision Agent for section: {section_title}...")
        
        prompt = f"""
        You are an expert academic editor and LaTeX formatter. You have been asked to revise a specific section ("{section_title}") of an academic paper.
        A meticulous peer reviewer has identified issues in this section that must be corrected. You have also been provided with the original context files necessary to ensure factual accuracy and avoid hallucination.
        
        Your task is to rewrite and correct this section to completely resolve the reviewer's feedback. Pay special attention to resolving logical contradictions, number discrepancies, and ensuring consistent terminology.
        
        Here is the reviewer's feedback for this section:
        \n---\n{section_feedback}\n---\n
        
        Here is the CURRENT DRAFT of the section:
        \n---\n{current_section_draft}\n---\n
        
        Here is the ORIGINAL EXPERIMENTAL CONTEXT for this section:
        \n---\n{section_context}\n---\n
        
        CRITICAL RULES:
        1. Output ONLY valid LaTeX code representing the FULL REVISED SECTION text.
        2. Do NOT include standard LaTeX frontmatter (e.g., \\documentclass, \\begin{{document}}).
        3. Ensure you keep the section heading (e.g., \\section{{{section_title}}}) at the beginning of the text to establish structure for the reviewer.
        4. Ensure no new packages are assumed or hallucinated.
        5. Resolve every required revision explicitly.
        6. Ensure all figures use width=\\linewidth and wide tables are scaled (e.g., using \\resizebox{{\\linewidth}}{{!}}{{...}}) to prevent overflowing the two-column format.
        """
        
        return await self._call_llm_text(prompt, temperature=0.3)

    async def fix_latex_errors(self, latex_source: str, error_log: str) -> str:
        """Agent responsible for fixing LaTeX compilation errors."""
        print("Executing LaTeX Fixer Agent...")
        
        prompt = f"""
        You are an expert LaTeX developer and debugger. The following complete LaTeX source code failed to compile using the `tectonic` compiler.
        
        Your task is to analyze the compiler's error log, identify the exact lines and commands that caused the failure, and fix them in the source code.
        
        Here is the ERROR LOG:
        \n---\n{error_log}\n---\n
        
        Here is the FULL LATEX SOURCE CODE:
        \n---\n{latex_source}\n---\n
        
        CRITICAL RULES:
        1. You MUST output ONLY the complete, fixed LaTeX source code.
        2. Do NOT output any explanation, markdown code blocks (e.g., ```latex), or conversational text.
        3. Ensure you fix ALL issues mentioned in the log (e.g., missing brackets, undefined control sequences, unescaped special characters, etc.).
        4. Do NOT alter the academic content, numbers, or logic of the paper. Only fix the structural LaTeX syntax errors.
        """
        
        return await self._call_llm_text(prompt, temperature=0.1)

    async def enrich_references(self, current_draft: str, existing_references_info: str) -> EnrichedDraft:
        """
        Agent responsible for identifying common techniques in the draft and supplementing classical references.
        This method MUST use Google Search directly via the gemini client, bypassing the shared llm_client 
        because the shared client doesn't explicitly support `GoogleSearch` as a tool declaration type.
        """
        print("Executing Reference Enrichment Agent (with Google Search Grounding)...")
        
        prompt = f"""
        You are an expert academic editor and bibliographer. The user has drafted a research paper, but the current bibliography is too sparse. 
        Your task is to enrich the paper by adding citations to well-known, classical techniques or algorithms mentioned in the text (e.g., PCA, SVM, ResNet, Transformer, Adam optimizer, etc.).
        
        Here is the FULL CURRENT DRAFT of the paper:
        \n---\n{current_draft}\n---\n
        
        Here are the EXISTING REFERENCES that are already in the bibliography. DO NOT duplicate these citation keys:
        \n---\n{existing_references_info}\n---\n
        
        CRITICAL RULES:
        1. Identify mentions of classical or foundational methods/models in the draft that do not currently have a citation (e.g., if you see "Support Vector Machine" without a \\cite{{...}}).
        2. Insert the appropriate \\cite{{citation_key}} command directly into the LaTeX text immediately following the technique's mention.
        3. Do NOT alter ANY experimental data, numerical results, logical flow, or the structure of the paper. Only insert \\cite{{...}} commands.
        4. Do NOT hallucinate empirical claims or change the author's narrative. 
        5. For every new \\cite{{citation_key}} you introduce, you MUST use your Google Search tool to verify the exact authors, year, title, and publication venue of the original paper before creating its BibTeX entry in the `new_references` output field. Do NOT rely solely on your internal memory; you must verify it to ensure 100% academic accuracy and prevent hallucination.
        6. Ensure the `citation_key` for your new references does NOT conflict with any existing references.
        7. Provide the ENTIRE updated LaTeX text in `updated_draft`, not just a snippet.
        
        You must return the result as a raw JSON string matching this schema:
        {EnrichedDraft.model_json_schema()}
        """
        
        # Local direct invocation to enable Grounding
        api_key = self.api_config.get("apiKey") or self.api_config.get("api_key") or ""
        local_client = genai.Client(api_key=api_key)
        
        try:
            # We use an exponential backoff loop similar to our old _generate_content_with_retry
            max_retries = 3
            delay = 3
            for attempt in range(max_retries):
                try:
                    response = await local_client.aio.models.generate_content(
                        model=self.api_config.get("model") or "gemini-2.5-pro",
                        contents=prompt,
                        config=types.GenerateContentConfig(
                            response_mime_type="application/json",
                            temperature=0.3,
                            tools=[{"google_search": {}}],
                        ),
                    )
                    
                    response_text = response.text or ""
                    response_text = re.sub(r'^```json\s*', '', response_text)
                    response_text = re.sub(r'\s*```$', '', response_text)
                    
                    data = json.loads(response_text)
                    return EnrichedDraft(**data)
                    
                except Exception as e:
                    if attempt < max_retries - 1:
                        await asyncio.sleep(delay)
                        delay *= 2
                    else:
                        raise e
        finally:
            try:
                await local_client.aio.aclose()
            except Exception:
                pass
